name: integrate & deploy

on:
  push:
    branches: [master, main]

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Building the client (clean install) 1/2
        run: npm --prefix 'client/' ci
      - name: Building the client (build) 2/2
        run: npm --prefix 'client/' run build

  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Building the server
        run: dotnet build 'server'

      - name: Testing the server
        run: dotnet test 'server/Tests'
  
  release:
    name: release
    needs: [client, server]
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}
      PORT: ${{ secrets.PORT }}
      KEY: ${{ secrets.KEY }}
    steps:
    - name: executing remote ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER }}
        port: ${{ env.PORT }}
        key: ${{ env.KEY }}
        script: |
          cd projects/Project_Odontologist
          git pull
          sudo docker compose build
          sudo docker compose up -d